#server:
#  port: 9821
spring:
  application:
    name: user-consumer
#  redis:
#    timeout: 3000
#    host: 127.0.0.1
#    port: 6379
#    jedis:
#      pool:
#        max-active: 10
#        max-wait: -1
#        max-idle: 8
##    session:
##      store-type: redis
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9801/eureka