#server:
#  port: 9811
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost/qrcode?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: liuliu
#  application:
#    name: user-provider
#
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9801/eureka/
