#server:
#  port: 9831
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost/qrcode?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: liuliu
#  application:
#    name: qrcode-provider
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9801/eureka
#
#
#
#
#
